### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by papafe** [jeppedl/DataMining#1]
Some comments on your code:
- You need some structure in your code. You should try to divide it in modules, where each module should deal with a specific function. Also separate the code from the data files (.txt)
- You should use pep8 and pyflake (flake8 check for both together) in order to check for style issues. Most IDEs can correct those issues almost automatically
- Update your README.md
- You need to test your code.
- Don't call a dictionary `dict`, because that is the name of a built-in data type, and things could get nasty.
- You need to comment and document your code, on modules, classes and functions.
- Check the slides from Vladimir on the noob errors. You have some of them. For instance, to loop through a list you are doing:

```
L = len(replyList)
i=0

while i< L:
  redcomment= replyList[i]
  do_something(redcomment)
```

instead of :

```
for redcomment in replyList:
    do_something(redcomment)
```

**Comment by bachnielsen** [comment]
Thank you Ferdinando for the comments. :+1:
